/* Common for timestamp incrementing BPF kernel prog and it's userland prog */
#ifndef __NUC_TS_COMMON_KERN_USER_H
#define __NUC_TS_COMMON_KERN_USER_H

enum stat_types {
	STAT_VERIFIERHAPPY = 0,
	STAT_ETHSHORT,
	STAT_VLANSHORT,
	STAT_NONIP,
	STAT_IPTOTSHORT,
	STAT_IPHDRSHORT,
	STAT_IP6EXTHDRSHORT,
	STAT_NONTCP,
	STAT_TCPSHORT,
	STAT_TCPINVALID,
	STAT_TCPOPTOVERFLOW,
	STAT_NONTSTAMP,
	STAT_TS_INCREMENTED,
	STAT_MAX, //keep last
};

/* keep in sync with above*/
static const char *stat_entry_names[STAT_MAX] = {
	[STAT_VERIFIERHAPPY]  = "BPFVERIFIER",
	[STAT_ETHSHORT]       = "ETHSHORT",
	[STAT_VLANSHORT]      = "VLANSHORT",
	[STAT_NONIP]          = "NONIP",
	[STAT_IPTOTSHORT]     = "IPTOTSHORT",
	[STAT_IPHDRSHORT]     = "IPHDRSHORT",
	[STAT_IP6EXTHDRSHORT] = "IP6EXTHDRSHORT",
	[STAT_NONTCP]         = "NONTCP",
	[STAT_TCPSHORT]       = "TCPSHORT",
	[STAT_TCPINVALID]     = "TCPINVALID",
	[STAT_TCPOPTOVERFLOW] = "TCPOPTOVERFLOW",
	[STAT_NONTSTAMP]      = "NONTSTAMP",
	[STAT_TS_INCREMENTED] = "TS_INCREMENTED",
};
#endif
